version: "3"
services:
  app:
    image: ufo:0.04
    volumes:
      - ./:/application
    ports:
      - 8080
    environment:
      - SERVICE_PORTS=8080
    # DB연결
    depends_on:
      - mysql
    # 컨테이너 생성시 DB컨테이너가 초기화 되기 전에 연결을 시도해서 서버가 뻗어버리는 현상 고치기위한 스크립트.
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh mysql:3306 -t 20
        npm start
    # 로드밸런싱 관련 설정
    deploy:
      replicas: 20
      update_config:
        parallelism: 5
        delay: 20s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    networks:
      - UFO

  mysql:
    image: mysql:8.0.17
    ports:
      - "3306:3306" # host에 mysql이 이미 있는경우 port 에러나서 수정
    environment:
      MYSQL_ROOT_PASSWORD: "root" # MYSQL 패스워드 설정 옵션
      MYSQL_DATABASE: "ufo"
    command: # 한글깨짐 방지
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/db:/var/lib/mysql
    networks:
      - UFO

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379" # bind 6000 to basic port 6379
    volumes:
      - ./database/redis/redis_data:/data
    environment:
      - REQUIREPASS=redispw
    networks:
      - UFO

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - app
      - mysql
      - redis
    # Balancing Algorithm
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    networks:
      - UFO
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  UFO:
    driver: overlay
